---
title: "Análise Descritiva"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: lualatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.width = 8.0,
                      fig.height = 4.0)
```

#Análise Descritiva - GeoLV

##Distribuição dos Indicadores

Vamos começar carrengando o banco de dados.

```{r, message=F}
library(tidyverse)
library(knitr)
library(plotly)
data <- read_rds("banco.rds")
```

Após, uma análise descritiva das variáveis.

```{r}
data %>% 
  ggplot(mapping = aes(x = dispersion)) +
  theme_minimal() +
  geom_histogram()

data %>% 
  summarise(`1º Quartil` = round(quantile(dispersion, 0.25, na.rm = T), 6),
            `Mediana`    = round(quantile(dispersion, 0.50, na.rm = T), 6),
            `3º Quartil` = round(quantile(dispersion, 0.75, na.rm = T), 6),
            `Média`      = round(mean(dispersion, na.rm = T), 6),
            `Desvio Padrão` = sd(dispersion, na.rm = T)) %>% 
  kable(caption = "Estatística descritiva da dispersão")
```

```{r}
data %>% 
  ggplot(mapping = aes(x = clusters_count)) +
  geom_bar() +
  scale_x_continuous(breaks = seq(1, 6, by = 1))
```

```{r}
data %>% 
  ggplot(mapping = aes(x = providers_count)) +
  geom_bar() +
  theme_minimal() +
  scale_x_continuous(breaks = seq(1, 3, by = 1))
```

## Distribuição dos Indicadores por Município

```{r}
data %>% 
  ggplot(mapping = aes(x = NM_LOCALIDADE, y = dispersion)) +
  geom_boxplot() + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 50, hjust = 1))
```

```{r, fig.height=5.0, fig.width=8.0}
data %>% 
  ggplot(mapping = aes(x = NM_LOCALIDADE, y = dispersion)) +
  geom_boxplot() + 
    theme_minimal() +
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) +
  ylim(c(0, 0.2))
```

```{r, fig.height=7.0, fig.width= 9.0}
data %>% 
  group_by(NM_LOCALIDADE) %>% 
  summarise(MEDIA = mean(clusters_count, na.rm = T)) %>% 
  mutate(DESVIO_MEDIA = (((MEDIA - mean(MEDIA))/mean(MEDIA)) * 100)) %>% 
  ggplot(mapping = aes(x = NM_LOCALIDADE, y = DESVIO_MEDIA)) +
  geom_segment(aes(xend = NM_LOCALIDADE, yend = 0, color = DESVIO_MEDIA > 0), alpha = 0.8, size = 2) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  scale_color_discrete(labels = c("Negativo", "Positivo")) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(y = "Desvio Percentual em Relação à Média (%)",
       x = "Municípios",
       color = "Direção do Desvio",
       title = "Diferença de Quantidade de Clusters")
```

```{r, fig.height=7.0, fig.width= 9.0}
data %>% 
  group_by(NM_LOCALIDADE) %>% 
  summarise(MEDIA = mean(providers_count, na.rm = T)) %>% 
  mutate(DESVIO_MEDIA = (((MEDIA - mean(MEDIA))/mean(MEDIA)) * 100)) %>% 
  ggplot(mapping = aes(x = NM_LOCALIDADE, y = DESVIO_MEDIA)) +
  geom_segment(aes(xend = NM_LOCALIDADE, yend = 0, color = DESVIO_MEDIA > 0), alpha = 0.8, size = 2) +
  geom_point(size = 2) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  scale_color_discrete(labels = c("Negativo", "Positivo")) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(y = "Desvio Percentual em Relação à Média (%)",
       x = "Municípios",
       color = "Direção do Desvio",
       title = "Diferença de Quantidade de Provedores")
```

```{r}
data %>% 
  ggplot(mapping = aes(x = clusters_count, y = providers_count, color = log(dispersion))) +
  geom_point() +
  geom_jitter()

ggplotly()
```
